(() => {
  const A=globalThis.AFC=globalThis.AFC||{}; let root, rail, track, preview, raf=0;
  const state={items:[],active:null,signature:''};
  const textOf=turn=>{const bubble=turn.querySelector('div.bubble.user');return (bubble?.textContent||'').replace(/\s+/g,' ').trim();};
  const scrollHost=()=>A.q(document,A.selectors.scroll).el||document.scrollingElement||document.documentElement;
  const hostMetrics=()=>{const host=scrollHost();const rootRect=host===document.scrollingElement?{top:0}:host.getBoundingClientRect();return {host,top:rootRect.top,scrollTop:host.scrollTop||0,height:host.scrollHeight||document.documentElement.scrollHeight||1,viewport:host.clientHeight||window.innerHeight};};
  const make=(tag,cls)=>{const el=document.createElement(tag);el.className=cls;el.dataset.afcUi='';return el;};
  const hidePreview=()=>{state.active=null;preview.hidden=true;};
  const showPreview=item=>{state.active=item;preview.textContent='';const title=make('strong','afc-minimap-preview-index');title.textContent=`رسالة المستخدم ${item.index}`;const body=make('span','afc-minimap-preview-text');body.textContent=item.text||'رسالة بدون نص';preview.append(title,body);const r=item.button.getBoundingClientRect();preview.style.top=`${Math.max(12,Math.min(window.innerHeight-120,r.top-8))}px`;preview.hidden=false;};
  const jump=item=>{const m=hostMetrics();const tr=item.turn.getBoundingClientRect();const target=m.scrollTop+(tr.top-m.top)-Math.max(24,(m.viewport-tr.height)/2);m.host.scrollTo({top:Math.max(0,target),behavior:'smooth'});};
  const updatePositions=()=>{raf=0;if(!rail||!root)return;const m=hostMetrics();const usable=Math.max(1,m.height);for(const item of state.items){const tr=item.turn.getBoundingClientRect();const absolute=m.scrollTop+(tr.top-m.top);const pct=Math.max(0,Math.min(1,absolute/usable));item.button.style.top=`${pct*100}%`;item.button.style.height=`${Math.max(4,Math.min(16,190/state.items.length))}px`;}};
  const render=()=>{if(!root)return;const turns=[...root.querySelectorAll(A.selectors.turn[0])].filter(t=>t.querySelector('div.bubble.user'));const signature=turns.map(t=>t.getAttribute('data-turn-id')||textOf(t).slice(0,32)).join('|');if(signature===state.signature){updatePositions();return;}state.signature=signature;state.items=turns.map((turn,i)=>({turn,index:i+1,text:textOf(turn),button:null}));track.textContent='';for(const item of state.items){const b=make('button','afc-minimap-item');b.type='button';b.setAttribute('aria-label',`الانتقال إلى رسالة المستخدم ${item.index}`);b.addEventListener('mouseenter',()=>showPreview(item));b.addEventListener('focus',()=>showPreview(item));b.addEventListener('mouseleave',hidePreview);b.addEventListener('blur',hidePreview);b.addEventListener('click',()=>jump(item));item.button=b;track.appendChild(b);}updatePositions();};
  const schedule=()=>{if(!raf)raf=requestAnimationFrame(updatePositions);};
  A.startMinimap=()=>{if(rail)return;root=scrollHost();rail=make('aside','afc-minimap');rail.setAttribute('aria-label','التنقل بين رسائل المستخدم');track=make('div','afc-minimap-track');preview=make('div','afc-minimap-preview');preview.hidden=true;rail.append(track,preview);document.body.appendChild(rail);render();const observer=new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes,...x.removedNodes].some(n=>n.nodeType===Node.ELEMENT_NODE&&!n.closest?.('[data-afc-ui]'))))render();});observer.observe(root,{subtree:true,childList:true});root.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule,{passive:true});};
})();
